[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = { version = "0.23", features = ["std"] }
rustls-pemfile = "2"
common = { path = "../common"}
image = "0.24"
winit = "0.28"
pixels = "0.13"
lz4_flex = "0.11"
turbojpeg = "1.3"
openh264 = "0.3"
