[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = "0.23"
rustls-pemfile = "2"
common = { path = "../common" }
scrap = "0.5"
image = "0.24"
lz4_flex = "0.11"
core-graphics = "0.23"
core-foundation = "0.9"
foreign-types-shared = "0.3"
objc = "0.2"